### PR TITLE
update ig packages

### PR DESCRIPTION
**Pull request by dkamburov**

### CODE REVIEW

**Comment by mddifilippo89** [comment]
@dkamburov Can you go back and update igniteui-webcomponents to v4.7.0 instead of downgrading to 4.5?

**Comment by dkamburov** [comment]
yeah, sure

**Comment by IMinchev64** [comment]
Apparently there is something in this update that causes the `Linear Progress Indicator Dynamic` sample to break. The button to decrease the progress only increases it.

Additionally, the grid samples break and throw the following error:
```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChildFromContainer (http://localhost:4200/static/js/bundle.js:29569:19)
    at commitDeletionEffectsOnFiber (http://localhost:4200/static/js/bundle.js:40596:19)
    at recursivelyTraverseDeletionEffects (http://localhost:4200/static/js/bundle.js:40562:9)
    at commitDeletionEffectsOnFiber (http://localhost:4200/static/js/bundle.js:40685:13)
    at recursivelyTraverseDeletionEffects (http://localhost:4200/static/js/bundle.js:40562:9)
    at commitDeletionEffectsOnFiber (http://localhost:4200/static/js/bundle.js:40685:13)
    at recursivelyTraverseDeletionEffects (http://localhost:4200/static/js/bundle.js:40562:9)
    at commitDeletionEffectsOnFiber (http://localhost:4200/static/js/bundle.js:40627:15)
    at recursivelyTraverseDeletionEffects (http://localhost:4200/static/js/bundle.js:40562:9)
    at commitDeletionEffectsOnFiber (http://localhost:4200/static/js/bundle.js:40589:15)
```

**Review by IMinchev64 — COMMENTED** [review]
Apparently there is something in this update that causes the `Linear Progress Indicator Dynamic` sample to break. The button to decrease the progress only increases it.

Additionally, the grid samples break and throw the following error:
```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChildFromContainer (http://localhost:4200/static/js/bundle.js:29569:19)
    at commitDeletionEffectsOnFiber (http://localhost:4200/static/js/bundle.js:40596:19)
    at recursivelyTraverseDeletionEffects (http://localhost:4200/static/js/bundle.js:40562:9)
    at commitDeletionEffectsOnFiber (http://localhost:4200/static/js/bundle.js:40685:13)
    at recursivelyTraverseDeletionEffects (http://localhost:4200/static/js/bundle.js:40562:9)
    at commitDeletionEffectsOnFiber (http://localhost:4200/static/js/bundle.js:40685:13)
    at recursivelyTraverseDeletionEffects (http://localhost:4200/static/js/bundle.js:40562:9)
    at commitDeletionEffectsOnFiber (http://localhost:4200/static/js/bundle.js:40627:15)
    at recursivelyTraverseDeletionEffects (http://localhost:4200/static/js/bundle.js:40562:9)
    at commitDeletionEffectsOnFiber (http://localhost:4200/static/js/bundle.js:40589:15)
```

**Comment by mddifilippo89** [comment]
[dkamburov](https://github.com/dkamburov) Stepper (linear) sample has a breaking change with index missing from the active step validation procedure. I just updated the sample so this PR doesn't break the browser. Someone should fix this sample so it behaves like WC.

**Review by MayaKirova — APPROVED** [review]

**Review by MayaKirova — APPROVED** [review]

**Pull request merged**
