### PR TITLE
added grid and hgrid remote paging samples

### PR DESCRIPTION
**Pull request by tishko0**

### CODE REVIEW

**Comment by MarielaTihova** [comment]
Found issue: 

HGgrid- Remote paging- console error

**Comment by MarielaTihova** [comment]
Found issue for **`Grid`**: (Paging is NOT working)

Ggrid- Remote paging- paging not working

**Comment by MarielaTihova** [comment]
Issue 3: for both `Grid` and  `HGrid`

When routing to remote paging sample from any other sample, these console errors appear:

image

Steps to reproduce:

1. Run all samples (browser folder)
2. Go to some random sample URL, for example http://localhost:4200/react-demos/samples/grids/hierarchical-grid/multi-column-headers-template
3. The go to the Remote paging sample URL: http://localhost:4200/react-demos/samples/grids/hierarchical-grid/remote-paging-hgrid

**Comment by MarielaTihova** [comment]
> Issue 2: for **`Grid`**: ( * ) Paging is NOT working for `remote-paging-data` example. (**) Paging is working for `remote-paging-grid` example. @tishko0 What is the relation between these two? Changes in this PR seem to be only for `remote-paging-grid`. Should we create a separate issue for ( * ) or is it something that is obsolete?
> 
> Ggrid- Remote paging- paging not working

Issue 2 -> RESOLVED

**Comment by MarielaTihova** [comment]
> Issue 3: for both `Grid` and `HGrid`
> 
> When routing to remote paging sample from any other sample, these console errors appear:
> 
> image
> Steps to reproduce:
> 
> 1. Run all samples (browser folder)
> 2. Go to some random sample URL, for example http://localhost:4200/react-demos/samples/grids/hierarchical-grid/multi-column-headers-template
> 3. The go to the Remote paging sample URL: http://localhost:4200/react-demos/samples/grids/hierarchical-grid/remote-paging-hgrid

Issue 3 persists. @tishko0 can you please have a look at it?

**Comment by tishko0** [comment]
> > Issue 3: for both `Grid` and `HGrid`
> > When routing to remote paging sample from any other sample, these console errors appear:
> > image
> > Steps to reproduce:
> > 
> > 1. Run all samples (browser folder)
> > 2. Go to some random sample URL, for example http://localhost:4200/react-demos/samples/grids/hierarchical-grid/multi-column-headers-template
> > 3. The go to the Remote paging sample URL: http://localhost:4200/react-demos/samples/grids/hierarchical-grid/remote-paging-hgrid
> 
> Issue 3 persists. @tishko0 can you please have a look at it?

removed errors ^^

**Comment by dkamburov** [comment]
@tishko0 there is a merge conflict

**Review by HUSSAR-mtrela — CHANGES_REQUESTED** [review]
Why did you remove NwindData.ts and index.tsx files in 
samples/grids/grid/remote-paging-data sample?

**Comment by dkamburov** [comment]
> Why did you remove NwindData.ts and index.tsx files in samples/grids/grid/remote-paging-data sample?

This is an old sample and it's not referenced nowhere, it's basically being removed in favor of the new one.

**Review by dkamburov — APPROVED** [review]

**Pull request merged**
